# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160910233805 on 2016-12-14 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=40)),
                ('eventplace', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.SignNer')),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
