# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160910233805 on 2016-12-16 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='about_event',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
