# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160910233805 on 2017-01-03 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_event_about_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='signner',
            name='reg_event',
            field=models.ManyToManyField(to='website.EvenT'),
        ),
    ]
