# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160910233805 on 2017-01-13 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170113_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signner',
            name='security',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
