# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160910233805 on 2017-01-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20170113_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Securing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.AddField(
            model_name='signner',
            name='answering',
            field=models.ManyToManyField(to='website.Securing'),
        ),
    ]
