# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160910233805 on 2017-01-14 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20170113_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200, null=True)),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
