# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160910233805 on 2017-01-15 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_answering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answering',
        ),
    ]
