# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160910233805 on 2017-01-15 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_answering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answering',
        ),
    ]
