# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160910233805 on 2017-01-15 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='signner',
            name='reg_question',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
