# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160910233805 on 2017-01-20 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_signner_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_img',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
