# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160910233805 on 2017-01-21 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_signner_userimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
