# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160910233805 on 2017-01-25 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
